name: Android CI Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: check structure
        run: |
          echo "current folder:"
          ls -F
          echo "Android folders"
          ls -F android || echo "not found"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: install gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: build
        run: |
          BUILD_FILE_PATH=$(find . -name "build.gradle*" | head -n 1)
          if [ -z "$BUILD_FILE_PATH" ]; then
            echo "no such file"
            exit 1
          fi
          
          DIR=$(dirname "$BUILD_FILE_PATH")
          if [[ "$DIR" == */app ]]; then
            DIR=$(dirname "$DIR")
          fi
          
          echo "will run build at: $DIR"
          cd "$DIR"
          gradle assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GDVN-App-Debug
          path: "**/build/outputs/apk/debug/*.apk"
